# Generated by Django 5.1.1 on 2024-09-20 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_alter_order_delivery_cost_alter_order_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_cost',
        ),
        migrations.RemoveField(
            model_name='order',
            name='grand_total',
        ),
    ]
