# Generated by Django 5.1.1 on 2024-09-11 19:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(0, 'Zero'), (1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')]), blank=True, null=True, size=None),
        ),
    ]
