# Generated by Django 5.1.1 on 2024-09-25 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_rating_remove_review_review_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
