# Generated by Django 5.1.1 on 2024-09-27 12:54

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('coffee', 'Coffee'), ('equipment', 'Equipment'), ('single', 'Single Origin'), ('blend', 'Blend'), ('seasonal', 'Seasonal'), ('sale', 'Sale'), ('bundle', 'Bundles')], max_length=50),
        ),
    ]
